version: '2'
services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/usr/src/app
    ports:
      - "8083:5000"
      - "3306"
    environment:
      - FLASK_LOG_FILE='/var/log/app/restbus-api/container.log'